#
# Abbruchbedingungen prüfen
#
- debug:
    msg: "Die Rolle ist nicht aktiviert: Abgebrochen für {{inventory_hostname}}"
  failed_when: 1
  when: role_cmk_agent_register_enabled != true

- debug:
    msg: "Dieser Server ist auf der Sperrliste: Abgebrochen für {{inventory_hostname}}."
  failed_when: 1
  when: inventory_hostname in excluded_hosts


# Vorarbeiten
- name: "Service-Fakten holen"
  ansible.builtin.service_facts:

# Installation des CMK-Agenten auf Hosts
- ansible.builtin.include_tasks: install_agent.yml

# Setup der Firewall
- ansible.builtin.include_tasks: setup_firewall.yml

# Setup der Hosts auf dem CMK-Server
- ansible.builtin.include_tasks: register_host.yml

# Überspielen der Zertifikatsdateien
- ansible.builtin.include_tasks: setup_tls.yml
